### ISSUE TITLE
My puma server stops working.

### ISSUE THREAD

**Issue by suratpyari** [seuros/capistrano-puma#102]
My puma server stops working very frequently. What could be the reason?

**Comment by seuros** [comment]
Not enough food (RAM) could be a reason. 
Do you have anything in the log file ?

**Comment by suratpyari** [comment]
So disk information is as follow:
```
df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      7.8G  5.9G  1.5G  80% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
udev            285M  8.0K  285M   1% /dev
tmpfs            59M  196K   59M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            295M     0  295M   0% /run/shm
none            100M     0  100M   0% /run/user
```

1 error I can see in access log very frequently is - 
```
=== puma startup: 2015-04-19 14:46:59 +0000 ===
/var/www/apps/printvogue/shared/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/binder.rb:284:in `add_unix_listener': There is already a server bound to: /var/www/apps/printvogue/shared/tmp/sockets/printvogue-puma.sock (RuntimeError)
	from /var/www/apps/printvogue/shared/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/binder.rb:124:in `block in parse'
	from /var/www/apps/printvogue/shared/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/binder.rb:82:in `each'
	from /var/www/apps/printvogue/shared/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/binder.rb:82:in `parse'
	from /var/www/apps/printvogue/shared/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/runner.rb:119:in `load_and_bind'
	from /var/www/apps/printvogue/shared/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/single.rb:79:in `run'
	from /var/www/apps/printvogue/shared/bundle/ruby/2.2.0/gems/puma-2.11.2/lib/puma/cli.rb:216:in `run'
	from /var/www/apps/printvogue/shared/bundle/ruby/2.2.0/gems/puma-2.11.2/bin/puma:10:in `<top (required)>'
	from /var/www/apps/printvogue/shared/bundle/ruby/2.2.0/bin/puma:23:in `load'
	from /var/www/apps/printvogue/shared/bundle/ruby/2.2.0/bin/puma:23:in `<main>'
```

**Comment by seuros** [comment]
Please use ruby 2.2.2

**Comment by suratpyari** [comment]
it still doesn't solve my issue. the issues generally occurs when there is image upload or image processing (like cropping the image)
