### ISSUE TITLE
Puma fails to start but i can start manually using same command

### ISSUE THREAD

**Issue by pitops** [seuros/capistrano-puma#188]
I run capistrano to deploy but at step where puma is about to start. I added trace below

However if i run the failing command manually it works. Any clues?

`bundle exec puma -C /home/deploy/apps/petfriend/shared/puma.rb --daemon`

Trace
```
** Execute puma:start
00:35 puma:start
      using conf file /home/deploy/apps/petfriend/shared/puma.rb
      01 bundle exec puma -C /home/deploy/apps/petfriend/shared/puma.rb --daemon
      01 bash: bundle: command not found
      01
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host petfriend.com.cy: Exception while executing on host petfriend.com.cy: Exception while executing on host petfriend.com.cy: puma exit status: 127
puma stdout: bash: bundle: command not found
puma stderr: Nothing written
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/runners/sequential.rb:31:in `rescue in run_backend'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/runners/sequential.rb:28:in `run_backend'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/runners/sequential.rb:22:in `execute'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/coordinator.rb:21:in `each'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/dsl.rb:54:in `on'
config/deploy.rb:78:in `block (2 levels) in <top (required)>'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/airbrussh-1.1.1/lib/airbrussh/rake/context.rb:62:in `execute'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/dsl/task_enhancements.rb:14:in `block in after'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/airbrussh-1.1.1/lib/airbrussh/rake/context.rb:62:in `execute'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/dsl.rb:15:in `invoke'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/tasks/framework.rake:64:in `block (2 levels) in <top (required)>'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/tasks/framework.rake:63:in `each'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/tasks/framework.rake:63:in `block in <top (required)>'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/airbrussh-1.1.1/lib/airbrussh/rake/context.rb:62:in `execute'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/application.rb:14:in `run'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/bin/cap:3:in `<top (required)>'
/Users/pitops/.rbenv/versions/2.3.1/bin/cap:23:in `load'
/Users/pitops/.rbenv/versions/2.3.1/bin/cap:23:in `<top (required)>'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:74:in `load'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:27:in `run'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli.rb:332:in `exec'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli.rb:20:in `dispatch'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli.rb:11:in `start'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/exe/bundle:34:in `block in <top (required)>'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/exe/bundle:26:in `<top (required)>'
/Users/pitops/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/pitops/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
SSHKit::Runner::ExecuteError: Exception while executing on host petfriend.com.cy: Exception while executing on host petfriend.com.cy: puma exit status: 127
puma stdout: bash: bundle: command not found
puma stderr: Nothing written
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
SSHKit::Runner::ExecuteError: Exception while executing on host petfriend.com.cy: puma exit status: 127
puma stdout: bash: bundle: command not found
puma stderr: Nothing written
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
SSHKit::Command::Failed: puma exit status: 127
puma stdout: bash: bundle: command not found
puma stderr: Nothing written
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/command.rb:100:in `exit_status='
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/backends/netssh.rb:148:in `execute_command'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/backends/abstract.rb:141:in `block in create_command_and_execute'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/backends/abstract.rb:141:in `tap'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/backends/abstract.rb:141:in `create_command_and_execute'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/backends/abstract.rb:74:in `execute'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capistrano-puma-e18b30c18ace/lib/capistrano/tasks/puma.rake:57:in `block (6 levels) in <top (required)>'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/backends/abstract.rb:93:in `with'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capistrano-puma-e18b30c18ace/lib/capistrano/tasks/puma.rake:56:in `block (5 levels) in <top (required)>'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/backends/abstract.rb:85:in `within'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capistrano-puma-e18b30c18ace/lib/capistrano/tasks/puma.rake:55:in `block (4 levels) in <top (required)>'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capistrano-puma-e18b30c18ace/lib/capistrano/tasks/puma.rake:134:in `puma_switch_user'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/capistrano-puma-e18b30c18ace/lib/capistrano/tasks/puma.rake:49:in `block (3 levels) in <top (required)>'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/backends/abstract.rb:29:in `run'
/Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.4/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => deploy:restart
The deploy has failed with an error: Exception while executing on host petfriend.com.cy: Exception while executing on host petfriend.com.cy: Exception while executing on host petfriend.com.cy: puma exit status: 127
puma stdout: bash: bundle: command not found
puma stderr: Nothing written
** Invoke deploy:failed (first_time)
** Execute deploy:failed


** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:


 DEBUG [10fc6c96] Running [ -f /home/deploy/apps/petfriend/shared/tmp/pids/puma.pid ] on petfriend.com.cy

 DEBUG [10fc6c96] Command: [ -f /home/deploy/apps/petfriend/shared/tmp/pids/puma.pid ]

 DEBUG [10fc6c96] Finished in 0.176 seconds with exit status 1 (failed).

  INFO [68cbde95] Running mkdir /home/deploy/apps/petfriend/shared/tmp/sockets -p on petfriend.com.cy

 DEBUG [68cbde95] Command: mkdir /home/deploy/apps/petfriend/shared/tmp/sockets -p

  INFO [68cbde95] Finished in 0.177 seconds with exit status 0 (successful).

  INFO [bcc071c3] Running mkdir /home/deploy/apps/petfriend/shared/tmp/pids -p on petfriend.com.cy

 DEBUG [bcc071c3] Command: mkdir /home/deploy/apps/petfriend/shared/tmp/pids -p

  INFO [bcc071c3] Finished in 0.182 seconds with exit status 0 (successful).

 DEBUG [1a831d24] Running [ -f /home/deploy/apps/petfriend/shared/puma.rb ] on petfriend.com.cy

 DEBUG [1a831d24] Command: [ -f /home/deploy/apps/petfriend/shared/puma.rb ]

 DEBUG [1a831d24] Finished in 0.177 seconds with exit status 0 (successful).

  INFO using conf file /home/deploy/apps/petfriend/shared/puma.rb

 DEBUG [686a031a] Running if test ! -d /home/deploy/apps/petfriend/current; then echo "Directory does not exist '/home/deploy/apps/petfriend/current'" 1>&2; false; fi on petfriend.com.cy

 DEBUG [686a031a] Command: if test ! -d /home/deploy/apps/petfriend/current; then echo "Directory does not exist '/home/deploy/apps/petfriend/current'" 1>&2; false; fi

 DEBUG [686a031a] Finished in 0.176 seconds with exit status 0 (successful).

  INFO [afca1ed2] Running bundle exec puma -C /home/deploy/apps/petfriend/shared/puma.rb --daemon on petfriend.com.cy

 DEBUG [afca1ed2] Command: cd /home/deploy/apps/petfriend/current && ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.3.1" RACK_ENV="production" ; bundle exec puma -C /home/deploy/apps/petfriend/shared/puma.rb --daemon )

 DEBUG [afca1ed2] 	bash: bundle: command not found

 DEBUG [afca1ed2]
```

**Comment by seuros** [comment]
install bundler in your server.

**Comment by pitops** [comment]
@seuros Please re-open the issue. Bundler is installed. If it was not, the bundle-install step of capistrano would not work.

**Comment by lyonsun** [comment]
I am running into the same issue, did you find out why? @pitops 

I also have installed bundler on the remote server: 

`current$ which bundler`
`/home/deployer/.rbenv/shims/bundler`

**Comment by Ethreal** [comment]
Any updates? I have the same issue

**Comment by Ethreal** [comment]
Ok, adding
`set :rbenv_map_bins, %w{rake gem bundle ruby rails puma pumactl}`
fixed the problem

**Comment by seuros** [comment]
You should not set rbenv_map_bins at all

**Comment by msyleung** [comment]
@Ethreal , thanks for your solution!
But I agree with @seuros, you should use 
`append :rbenv_map_bins, 'puma', 'pumactl'` instead of `set :rbenv_map_bins, %w{rake gem bundle ruby rails puma pumactl}` since it may be used by other plugins.

**Comment by Gaolz** [comment]
@msyleung Thank you. Solve my problem by your answer.

**Comment by bhaveshf-cuelogic** [comment]
@msyleung : In which file do we need to mention `append :rbenv_map_bins, 'puma', 'pumactl'` ?

**Comment by msyleung** [comment]
@bhaveshf-cuelogic  `config/deploy.rb`

**Comment by Reyzapermanasaputra** [comment]
I downgrade capistrano3-puma 2.00 to capistrano3-puma (1.2.1). Fixed My the problem

**Comment by imranrrr** [comment]
@msyleung - I am still facing this issue

**Comment by shoaibrex** [comment]
> @msyleung - I am still facing this issue puma.socket is not creating under shared/tmp/socket/

I am in the similar situation and my puma is not running  even though i have added  `append :rbenv_map_bins, 'puma', 'pumactl'`.
Were you able to solve this issue?
