### ISSUE TITLE
Wrong environment when depoying, right one when using cap puma:start

### ISSUE THREAD

**Issue by FloHeinle** [seuros/capistrano-puma#193]
Hi, 

thank you very much for this great gem.

I am getting an error when deploying:
```
E, [2017-01-17T15:27:02.720303 #17582] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
E, [2017-01-17T15:27:02.720972 #17603] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
E, [2017-01-17T15:27:02.744008 #17589] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
E, [2017-01-17T15:27:02.755346 #17596] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
/home/.../server/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/connection_specification.rb:248:in `resolve_symbol_connection': 'test' database is not configured. Available: ["staging"] (ActiveRecord::AdapterNotSpecified)
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/connection_specification.rb:211:in `resolve_connection'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/connection_specification.rb:169:in `spec'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_handling.rb:50:in `establish_connection'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/railtie.rb:120:in `block (2 levels) in <class:Railtie>'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/lazy_load_hooks.rb:27:in `each'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/railtie.rb:116:in `block in <class:Railtie>'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/initializable.rb:30:in `run'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/.../.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /home/.../.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/.../.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/.../.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/.../.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /home/.../.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /home/.../.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/.../.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /home/.../.rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/application.rb:352:in `initialize!'
	from /home/.../server/current/config/environment.rb:5:in `<top (required)>'
	from /home/.../server/current/config.ru:3:in `require'
	from /home/.../server/current/config.ru:3:in `block in <main>'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
	from /home/.../server/current/config.ru:in `new'
	from /home/.../server/current/config.ru:in `<main>'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:49:in `eval'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:49:in `new_from_string'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:40:in `parse_file'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb:313:in `load_rackup'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb:242:in `app'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/runner.rb:123:in `load_and_bind'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/cluster.rb:370:in `run'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/launcher.rb:172:in `run'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/cli.rb:74:in `run'
	from /home/.../server/shared/bundle/ruby/2.3.0/gems/puma-3.4.0/bin/puma:10:in `<top (required)>'
	from /home/.../server/shared/bundle/ruby/2.3.0/bin/puma:22:in `load'
	from /home/.../server/shared/bundle/ruby/2.3.0/bin/puma:22:in `<main>'
```
 when I run `cap puma:start `everything works as expected.

Some more info:

Capfile:
```
...
require 'capistrano/puma'
require 'capistrano/puma/workers'
require 'capistrano/puma/nginx'
...
```
deploy.rb
```
...
lock '3.7.1'
...
######### Puma
set :puma_conf, "#{shared_path}/config/puma.rb"
set :puma_threads, [1, 6]
set :puma_workers, 4
set :puma_init_active_record, true
set :puma_preload_app, true
set :puma_env, fetch(:rack_env, fetch(:rails_env, 'production'))
set :nginx_use_ssl, true
...
```
puma.rb

```
#!/usr/bin/env puma

directory '/home/.../server/current'
rackup "/home/.../server/current/config.ru"
environment 'staging'

pidfile "/home/.../server/shared/tmp/pids/puma.pid"
state_path "/home/.../server/shared/tmp/pids/puma.state"
stdout_redirect '/home/.../server/shared/log/puma_access.log', '/home/.../server/shared/log/puma_error.log', true

threads 1,6
bind 'unix:///home/.../server/shared/tmp/sockets/puma.sock'
workers 4

preload_app!

on_restart do
  puts 'Refreshing Gemfile'
  ENV["BUNDLE_GEMFILE"] = "/home/.../server/current/Gemfile"
end

on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end
```

Do you have an idea, what could cause this?
Thank you very much.

Bests
Flo

**Comment by Evgeniy28** [comment]
Change 
```rb
# puma.rb
environment 'production'
```
Then
```sh
cap staging puma:start
```
I had such a problem, when I'm started staging environment on vagrant machine! I hope this will solve your problem!

**Comment by FloHeinle** [comment]
Hi Evgeniy28,

as I wrote `cap staging puma:start` works as expected, but the puma:restart task which is executed during a deployment, wont work.

Cheers

**Comment by Evgeniy28** [comment]
```sh
'test' database is not configured
```
I think your problem is here!

**Comment by FloHeinle** [comment]
yes, but when deploying with staging environment, then I usually dont need the test db, right?
