### ISSUE TITLE
Failed to execute the monit command during deploy.

### ISSUE THREAD

**Issue by gogo52cn** [seuros/capistrano-puma#227]
Rails 5.1
Ruby 2.4.1
Cap 3.7.1

```
** Invoke puma:monit:monitor (first_time)
** Execute puma:monit:monitor
** Invoke puma:monit:config (first_time)
** Execute puma:monit:config
05:38 puma:monit:config
      Uploading /tmp/monit.conf 100.0%
Warning: `execute' should be wrapped in an `on' scope in /Users/*/.rvm/gems/ruby-2.4.1/gems/capistrano-3.7.1/lib/capistrano/dsl.rb:38.

  task :example do
    on roles(:app) do
      execute 'whoami'
    end
  end

cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as root@120.*.*.240: Exception while executing as root@120.*.*.240: undefined method `execute' for main:Object
/Users/*/.rvm/gems/ruby-2.4.1/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/Users/*/.rvm/gems/ruby-2.4.1/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
SSHKit::Runner::ExecuteError: Exception while executing as root@120.*.*.240: undefined method `execute' for main:Object
/Users/*/.rvm/gems/ruby-2.4.1/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/Users/*/.rvm/gems/ruby-2.4.1/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
NoMethodError: undefined method `execute' for main:Object
/Users/*/.rvm/gems/ruby-2.4.1/gems/capistrano-3.7.1/lib/capistrano/dsl.rb:83:in `execute'
/Users/*/.rvm/gems/ruby-2.4.1/gems/capistrano-3.7.1/lib/capistrano/dsl.rb:38:in `sudo'
/Users/*/.rvm/gems/ruby-2.4.1/gems/capistrano3-puma-3.1.0/lib/capistrano/puma/monit.rb:25:in `sudo_if_needed'
/Users/*/.rvm/gems/ruby-2.4.1/gems/capistrano3-puma-3.1.0/lib/capistrano/tasks/monit.rake:9:in `block (4 levels) in eval_rakefile'
/Users/*/.rvm/gems/ruby-2.4.1/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/*/.rvm/gems/ruby-2.4.1/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:29:in `run'
/Users/*/.rvm/gems/ruby-2.4.1/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => puma:monit:monitor
The deploy has failed with an error: Exception while executing as root@120.*.*.240: Exception while executing as root@120.*.*.240: undefined method `execute' for main:Object
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```

**Comment by xiaohui-zhangxh** [comment]
This bug has been fixed from Git source, but haven't released to rubygems.org, so `gem 'capistrano3-puma', github: "seuros/capistrano-puma"` can get rid of this error

**Comment by lidashuang** [comment]
@xiaohui-zhangxh 

I add `'capistrano3-puma', github: "seuros/capistrano-puma"` to Gemfile
and Failed to execute the monit command during deploy 


![image](https://cloud.githubusercontent.com/assets/612381/26047455/d4a393ba-3985-11e7-8f1d-4495dbc988f8.png)

![image](https://cloud.githubusercontent.com/assets/612381/26047473/ec128e98-3985-11e7-9d89-d49b51506da6.png)
