### ISSUE TITLE
undefined method `as' for #<Capistrano::Puma:0x005612a7210ec0>

### ISSUE THREAD

**Issue by jack-nie** [seuros/capistrano-puma#236]
Rails 5.1.0
Ruby 2.2.2
Cap 3.8.1
capistrano3-puma (3.1.0)

```
** Invoke puma:smart_restart (first_time)
** Execute puma:smart_restart
** Invoke puma:restart (first_time)
** Execute puma:restart
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host 192.168.10.102: undefined method `as' for #<Capistrano::Puma:0x005612a7210ec0>
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
NoMethodError: undefined method `as' for #<Capistrano::Puma:0x005612a7210ec0>
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/capistrano3-puma-3.1.0/lib/capistrano/puma.rb:11:in `puma_switch_user'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/capistrano3-puma-3.1.0/lib/capistrano/tasks/puma.rake:64:in `block (5 levels) in eval_rakefile'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:85:in `within'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/capistrano3-puma-3.1.0/lib/capistrano/tasks/puma.rake:63:in `block (4 levels) in eval_rakefile'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:29:in `run'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => puma:restart
The deploy has failed with an error: Exception while executing on host 192.168.10.102: undefined method `as' for #<Capistrano::Puma:0x005612a7210ec0>
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```

**Comment by jack-nie** [comment]
same as https://github.com/seuros/capistrano-puma/issues/229
