### ISSUE TITLE
puma:restart related to deploy doesn't work

### ISSUE THREAD

**Issue by mdesantis** [seuros/capistrano-puma#237]
capistrano (3.8.2)
capistrano3-puma (3.1.0)
capistrano-rbenv (2.1.1)
capistrano-bundler (1.2.0)
puma (3.9.1)

In `config/deploy.rb`:

```ruby
set :rbenv_map_bins, %w(rake gem bundle ruby rails puma pumactl sidekiq sidekiqctl)
```

---

When I deploy, puma:restart says it went ok:

```
02:20 puma:restart
      01 $HOME/.rbenv/bin/rbenv exec bundle exec pumactl -S /home/user/app/shared/tmp/pids/puma.state -F /home/user/app/shared/config/puma.rb restart
      01 Command restart sent success
    ✔ 01 user@server 0.780s
```

 but the app didn't restart, and in the log there is this error:

```
==> log/puma_error.log <==
/home/user/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem puma (>= 0.a) (Gem::GemNotFoundException)
  from /home/user/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems.rb:298:in `activate_bin_path'
  from /home/user/app/shared/bundle/ruby/2.4.0/bin/puma:22:in `<main>'
```

Instead, if I restart manually running `cap puma:restart` after the deploy it works:

```
> cap stage puma:restart
00:00 puma:start
      using conf file /home/user/app/shared/config/puma.rb
      01 $HOME/.rbenv/bin/rbenv exec bundle exec puma -C /home/user/app/shared/config/puma.rb --daemon
      01 Puma starting in single mode...
      01
      01 * Version 3.9.1 (ruby 2.4.1-p111), codename: Private Caller
      01
      01 * Min threads: 0, max threads: 16
      01
      01 * Environment: staging
      01
      01 * Daemonizing...
      01
    ✔ 01 user@server 0.800s
```

Maybe something related to rbenv?

**Comment by seuros** [comment]
don't set rbenv_map_bins. 

Also it seem you missing capistrano-bundler in your Gemfile.

**Comment by mdesantis** [comment]
capistrano-bundler is version 1.2.0. Why shouldn't I set rbenv_map_bins?

**Comment by mdesantis** [comment]
ah you mean append? yeah its the same i guess

**Comment by seuros** [comment]
> Why shouldn't I set rbenv_map_bins?
the gems are doing that for you.

I'm going to fix the bug with the latest capistrano

**Comment by mdesantis** [comment]
Seems to be a bundler error: https://github.com/bundler/bundler/issues/4576

**Comment by augustosamame** [comment]
+1

**Comment by glebtv** [comment]
Have the same problem, without rbenv or anything.
Also restarting just via pumactl without capistrano seems to do the same thing, so don't think it is a capistrano-puma problem

**Comment by glebtv** [comment]
Seems to be this bug: https://github.com/puma/puma/issues/1308

**Comment by jeffling** [comment]
FYI the workaround is this: 

```
require 'bundler/setup'
on_restart do
  ENV.replace(Bundler.clean_env)
end
```

How would you recommend we incorporate it to the generated puma config? If I weren't using capistrano-puma I would put it into my puma.rb directly. 

Or am I misunderstanding something here? I'm pretty new to the rails ecosystem :)

**Comment by sushant12** [comment]
facing the same issue

**Comment by tagliala** [comment]
fwiw, the workaround doesn't work for me (puma 3.9.1)

**Comment by DemisBand** [comment]
same issue

**Comment by mdesantis** [comment]
Workaround: `gem 'puma', '3.8.1'`

**Comment by borlafdev** [comment]
Just faced this today after deploying a new app, downgrading like @mdesantis says, works fine

**Comment by prashantvithani** [comment]
I downgraded Puma to 3.8.2, but I'm still facing similar issue after deployment. My system configuration contains 3 servers, there's always one or two server, in which Puma won't restart after deployment. Though, the deployment log says `Command restart sent success`.

Then, I logged in to all servers, and ran `ps aux | grep puma`. The output was weird.

**Server 1:** puma works fine, restarted successfully at `10:06` with release `20170726095950`
```
deploy   21379  0.0  3.5 2119668 274772 ?      Sl   10:06   0:01 puma 3.8.2 (unix:///var/www/fbdash/shared/tmp/sockets/puma.sock) [20170726095950]                                                        
deploy   21384  0.7  8.0 2266296 618124 ?      Sl   10:06   0:35 puma: cluster worker 0: 21379 [20170726095950]                                                                                           
deploy   21387  0.9  7.9 2269380 607296 ?      Sl   10:06   0:46 puma: cluster worker 1: 21379 [20170726095950]                                                                                           
deploy   21390  1.0  7.4 2271436 569760 ?      Sl   10:06   0:48 puma: cluster worker 2: 21379 [20170726095950]                                                                                           
deploy   21394  0.8  7.8 2203948 603500 ?      Sl   10:06   0:41 puma: cluster worker 3: 21379 [20170726095950]                                                                                           
deploy   25204  0.0  0.0  10484  2260 pts/2    S+   11:26   0:00 grep --color=auto puma
```

**Server 2:** Same as server 1, puma works fine, restarted successfully at `10:06` with release `20170726095950`
```
deploy   21379  0.0  3.5 2119668 274772 ?      Sl   10:06   0:01 puma 3.8.2 (unix:///var/www/fbdash/shared/tmp/sockets/puma.sock) [20170726095950]                                                        
deploy   21384  0.7  8.0 2266296 618124 ?      Sl   10:06   0:35 puma: cluster worker 0: 21379 [20170726095950]                                                                                           
deploy   21387  0.9  7.9 2269380 607296 ?      Sl   10:06   0:46 puma: cluster worker 1: 21379 [20170726095950]                                                                                           
deploy   21390  1.0  7.4 2271436 569760 ?      Sl   10:06   0:48 puma: cluster worker 2: 21379 [20170726095950]                                                                                           
deploy   21394  0.8  7.8 2203948 603500 ?      Sl   10:06   0:41 puma: cluster worker 3: 21379 [20170726095950]                                                                                           
deploy   25204  0.0  0.0  10484  2260 pts/2    S+   11:26   0:00 grep --color=auto puma
```

**_**Server 3:** Two of the clusters stopped (Didn't restart at all), still pointing at **old release** `20170726080157`_**
```
deploy   22364  0.0  3.6 2120888 279128 ?      Sl   09:37   0:00 puma 3.8.2 (unix:///var/www/fbdash/shared/tmp/sockets/puma.sock) [20170726080157]                                                                                                                             
deploy   22369  0.1  9.3 2405448 719184 ?      Sl   09:37   0:11 puma: cluster worker 0: 22364 [20170726080157]                                                                                                                                                                
deploy   22378  0.2 10.9 2538956 838948 ?      Sl   09:37   0:15 puma: cluster worker 3: 22364 [20170726080157]                                                                                                                                                                
deploy   30422  0.0  0.0  10484  2160 pts/2    S+   11:26   0:00 grep --color=auto puma
```
This is causing all requests that are directed to this server to timeout with error code HTTP 408.

Any idea why this is happening?

**Comment by uzzz** [comment]
@prashantvithani Looks like 3.8.2 has the same issue (at least I didn't notice any changes with 3.9.*), try downgrading it to 3.8.1. Worked for me

**Comment by aligo** [comment]
`bundle exec pumactl phased-restart`

same issue, 3.8.1 works fine.

tried `on_restart` fix, not works.

**Comment by vizcay** [comment]
This is a puma problem, look at https://github.com/puma/puma/issues/1308. Downgrading to 3.8.1 worked for me.

**Comment by tagliala** [comment]
Hi, Could  this https://github.com/puma/puma/issues/1308#issuecomment-320466307 be useful for a fix?

**Comment by Lukom** [comment]
I have the same problem with restarting. I have tried several fixes proposed here and they worked for me:

    gem 'puma', '3.9.1' #=> don't work
    gem 'puma', '3.8.2' #=> works!
    gem 'puma', git: 'https://github.com/grosser/puma.git', branch: 'grosser/fix' #=> works!

I will stick with official 3.8.2 version so far.

**Comment by vuhailuyen1991** [comment]
Same issue with version 3.9.1
Version 3.8.2 works like a charm. 
(Digital Ocean Ubuntu 16.04.3 - ruby 2.4.1)

**Comment by tagliala** [comment]
Hi,

puma 3.10.0 works for me!

**Comment by soigy** [comment]
Nice info. puma 3.10.0 works for me too!

**Comment by guillaumebriday** [comment]
Hey!
 
I have the exact same issue with puma 4. Do you have any solution?

Thank you for you work!

**Comment by hron84** [comment]
@guillaumebriday if phased restart by signals work on the server, you could try `kill -USR1 #{shared_path}/tmp/pids/puma.pid` in the script too.

**Comment by mateuyabar** [comment]
Same issue with puma 4.3.3, with capistrano3-puma 4.0.0

After deploy restart is sent, but puma is not started.

**Comment by muhammadyana** [comment]
Same issue with puma 4.3.3, with capistrano3-puma 4.0.0

After deploy restart is sent, but puma is not started.

**Comment by guillaumebriday** [comment]
I would like to help but I have no idea where to start, anyone could provide tips in order to submit a PR eventually ? 🙏 

How people deploy in production puma with capistrano if not with this gem? I don't understand how this issue could have been open for so long 🤔 

Thanks!

**Comment by augustosamame** [comment]
I have a "standard" deploy script I use in all my projects, and I have
added the following line to it:

    after "deploy", "puma:start"

workaround has been working fine for a couple of years now.

**Comment by giapnhdev** [comment]
A simple solution is adding `puma:start` after deploy finished

```
namespace :deploy do 
....do something
end

after :deploy, "puma:start"
```

**Comment by guillaumebriday** [comment]
@giapnhdev Is it as smooth as a regular restart of puma ? Thank you

**Comment by seuros** [comment]
@guillaumebriday , no .

It mean their server fail to restart and has to be restarted manually.

Maybe their server is lacking memory to spawn another instance before killing the first one.

I think i will add an option to do hard restart (stop:start).

**Comment by giapnhdev** [comment]
> @giapnhdev Is it as smooth as a regular restart of puma ? Thank you

Yes. I used it and it works perfectly!

**Comment by muhammadyana** [comment]
> A simple solution is adding `puma:start` after deploy finished
> 
> ```
> namespace :deploy do 
> ....do something
> end
> 
> after :deploy, "puma:start"
> ```

hello @giapnhdev  i use this trick but it still not work 

```
00:32 puma:restart
      01 ~/.rvm/bin/rvm 2.6.3 do bundle exec pumactl -S /home/deploy/apps/core-dev/shared/tmp/pids/puma.state -F /home/deploy/apps/hermina-core-dev/sha…
      01 Command restart sent success
    ✔ 01 deploy@47.241.6.19 1.061s
00:29 puma:start
      using conf file /home/deploy/apps/core-dev/shared/puma.rb
      Already Puma is running
```


puma already running, but when i open the web puma is not started.

**Comment by giapnhdev** [comment]
@muhammadyana Could you try
```
after :deploy, "puma:stop"
after :deploy, "puma:start"
```

**Comment by guillaumebriday** [comment]
@giapnhdev This is the only workaround I found but it has a downtime when a proper restart does not.

**Comment by muhammadyana** [comment]
> @muhammadyana Could you try
> 
> ```
> after :deploy, "puma:stop"
> after :deploy, "puma:start"
> ```

@giapnhdev  still not work

```
01:00 puma:restart
      01 ~/.rvm/bin/rvm 2.6.3 do bundle exec pumactl -S /home/deploy/apps/core-dev/shared/tmp/pids/puma.state -F /home/deploy/apps/core-dev/shared/puma.rb restart
      01 Command restart sent success
    ✔ 01 deploy@147.139.169.173 1.926s
01:03 puma:stop
      01 ~/.rvm/bin/rvm 2.6.3 do bundle exec pumactl -S /home/deploy/apps/core-dev/shared/tmp/pids/puma.state -F /home/deploy/apps/core-dev/shared/puma.rb stop
      01 No pid '3764' found
#<Thread:0x00007fa2dc8e3150@/Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	15: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
	14: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:31:in `run'
	13: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	12: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/capistrano3-puma-4.0.0/lib/capistrano/tasks/puma.rake:38:in `block (4 levels) in eval_rakefile'
	11: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:92:in `within'
	10: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/capistrano3-puma-4.0.0/lib/capistrano/tasks/puma.rake:39:in `block (5 levels) in eval_rakefile'
	 9: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/capistrano3-puma-4.0.0/lib/capistrano/puma.rb:9:in `puma_switch_user'
	 8: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/capistrano3-puma-4.0.0/lib/capistrano/tasks/puma.rake:40:in `block (6 levels) in eval_rakefile'
	 7: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:100:in `with'
	 6: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/capistrano3-puma-4.0.0/lib/capistrano/tasks/puma.rake:43:in `block (7 levels) in eval_rakefile'
	 5: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:80:in `execute'
	 4: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
	 3: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `tap'
	 2: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
	 1: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/netssh.rb:170:in `execute_command'
/Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/command.rb:97:in `exit_status=': pumactl exit status: 1 (SSHKit::Command::Failed)
pumactl stdout: No pid '3764' found
pumactl stderr: Nothing written
pumactl stdout: No pid '3764' found
pumactl stderr: Nothing written
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@147.139.169.173: pumactl exit status: 1
pumactl stdout: No pid '3764' found
pumactl stderr: Nothing written

Caused by:
SSHKit::Command::Failed: pumactl exit status: 1
pumactl stdout: No pid '3764' found
pumactl stderr: Nothing written

Tasks: TOP => puma:stop
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@147.139.169.173: pumactl exit status: 1
pumactl stdout: No pid '3764' found
pumactl stderr: Nothing written
```

i have made custom task like 
```
desc 'Start Puma Server'
task :start_puma do
  on roles(:app), in: :sequence, wait: 1 do
    execute("cd #{deploy_to}/current/ && ~/.rvm/bin/rvm #{fetch(:rvm_ruby_version)} do bundle exec puma -C #{deploy_to}/shared/puma.rb --daemon") 
  end
end
```

it work 😬

**Comment by muhammadyana** [comment]
> @muhammadyana Could you try
> 
> ```
> after :deploy, "puma:stop"
> after :deploy, "puma:start"
> ```

@giapnhdev  still not work

```
01:00 puma:restart
      01 ~/.rvm/bin/rvm 2.6.3 do bundle exec pumactl -S /home/deploy/apps/core-dev/shared/tmp/pids/puma.state -F /home/deploy/apps/core-dev/shared/puma.rb restart
      01 Command restart sent success
    ✔ 01 deploy@ipaddress 1.926s
01:03 puma:stop
      01 ~/.rvm/bin/rvm 2.6.3 do bundle exec pumactl -S /home/deploy/apps/core-dev/shared/tmp/pids/puma.state -F /home/deploy/apps/core-dev/shared/puma.rb stop
      01 No pid '3764' found
#<Thread:0x00007fa2dc8e3150@/Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	15: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
	14: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:31:in `run'
	13: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	12: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/capistrano3-puma-4.0.0/lib/capistrano/tasks/puma.rake:38:in `block (4 levels) in eval_rakefile'
	11: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:92:in `within'
	10: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/capistrano3-puma-4.0.0/lib/capistrano/tasks/puma.rake:39:in `block (5 levels) in eval_rakefile'
	 9: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/capistrano3-puma-4.0.0/lib/capistrano/puma.rb:9:in `puma_switch_user'
	 8: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/capistrano3-puma-4.0.0/lib/capistrano/tasks/puma.rake:40:in `block (6 levels) in eval_rakefile'
	 7: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:100:in `with'
	 6: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/capistrano3-puma-4.0.0/lib/capistrano/tasks/puma.rake:43:in `block (7 levels) in eval_rakefile'
	 5: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:80:in `execute'
	 4: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
	 3: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `tap'
	 2: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
	 1: from /Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/backends/netssh.rb:170:in `execute_command'
/Users/yana/.rvm/gems/ruby-2.6.3/gems/sshkit-1.21.0/lib/sshkit/command.rb:97:in `exit_status=': pumactl exit status: 1 (SSHKit::Command::Failed)
pumactl stdout: No pid '3764' found
pumactl stderr: Nothing written
pumactl stdout: No pid '3764' found
pumactl stderr: Nothing written
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@ipaddress: pumactl exit status: 1
pumactl stdout: No pid '3764' found
pumactl stderr: Nothing written

Caused by:
SSHKit::Command::Failed: pumactl exit status: 1
pumactl stdout: No pid '3764' found
pumactl stderr: Nothing written

Tasks: TOP => puma:stop
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@ipaddress: pumactl exit status: 1
pumactl stdout: No pid '3764' found
pumactl stderr: Nothing written
```

i set puma_bind like this, 
```
set :puma_bind,       ["tcp://0.0.0.0:7001", "unix://#{shared_path}/tmp/sockets/#{fetch(:application)}-puma.sock"]
```

but when i set just one it work, but when set in two multiple bind it return error like in top

**Comment by milkfarm** [comment]
I'm experiencing the same issue.

Calling `start` after the failed `restart` results in:
```
00:23 puma:restart
      01 ~/.rvm/bin/rvm default do bundle exec pumactl -S /var/www/pandemics/shared/tmp/pids/puma.state -F /var/www/pandemics/shared/puma.rb restart
      01 Command restart sent success
    ✔ 01 rails@pandemics.childsworld.com 1.053s
00:24 puma:start
      using conf file /var/www/pandemics/shared/puma.rb
      Already Puma is running
```

Calling `stop` and `start` after the failed `restart` results in:
```
00:22 puma:restart
      01 ~/.rvm/bin/rvm default do bundle exec pumactl -S /var/www/pandemics/shared/tmp/pids/puma.state -F /var/www/pandemics/shared/puma.rb restart
      01 Command restart sent success
    ✔ 01 rails@pandemics.childsworld.com 1.244s
00:23 puma:stop
      01 ~/.rvm/bin/rvm default do bundle exec pumactl -S /var/www/pandemics/shared/tmp/pids/puma.state -F /var/www/pandemics/shared/puma.rb stop
      01 No pid '2840' found
#<Thread:0x00007fdf1c220530 /Users/tim/.rvm/gems/ruby-2.7.1@pandemics/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
```

**Comment by milkfarm** [comment]
It's not pretty but sleeping for a few seconds works:
```
namespace :puma do
  desc 'Sleep for a few seconds then start puma'
  task :sleepy_start do
    sleep(10)
    invoke 'puma:start'
  end
  after :deploy, 'puma:sleepy_start'
end
```

**Comment by vast** [comment]
Hi guys,

In my case restart fails due to bundler error:
```ruby
==> log/puma_error.log <==
/home/deploy/.rbenv/versions/2.7.1/bin/bundle:23:in `load': cannot load such file -- /home/deploy/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle (LoadError)
	from /home/deploy/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
```

I tried reinstalling bundler. Still no luck.

Any ideas?

**Comment by johnwmcarneiro** [comment]
@vast I had the same problem, I use Rails 6. I solved when I did override the task.
In my `config/deploy.rb` I added the bellow code.

```
namespace :puma do
  Rake::Task[:restart].clear_actions

  desc "Overwritten puma:restart task"
  task :restart do
    puts "Overwriting puma:restart to ensure that puma is running. Effectively, we are just starting Puma."
    puts "A solution to this should be found."
    invoke "puma:stop"
    invoke "puma:start"
    invoke "puma:nginx_restart"
  end
end
```
I used this link as a reference https://stackoverflow.com/questions/44763777/capistrano-pumarestart-not-working-but-pumastart-does
I hope that helps you

**Comment by tagliala** [comment]
```
    invoke "puma:stop"
    invoke "puma:start"
```

If I'm correct, this is way different from `puma:restart`, because it will not perform a hot restart and you may loose requests during the deploy. I do not advise to do that, please correct me if I'm wrong

Ref: https://github.com/puma/puma/blob/master/docs/restart.md#normal-vs-hot-vs-phased-restart

**Comment by guillaumebriday** [comment]
@tagliala You're right. That's why it's still an issue.

Maybe with the support of systemd in Puma 5 the problem will be gone, I hope.

**Comment by guillaumebriday** [comment]
@nateberkopec Do you have any idea/suggestion to fix that? That would be awesome to be able to use Puma with capistrano in a seamless way 🙏 Thanks

**Comment by jmuheim** [comment]
Any news on that? Since upgrading to Rails 6 I seem to have this problem too.

**Comment by mdesantis** [comment]
@jmuheim it's likely not a problem on this gem (tho I appreciate that @seuros left this issue open, as it helps getting to know that this bug still happens); it's likely to be an issue on certain versions Puma maybe combined with certain versions of Bundler and / or certain versions of Rails :-/

**Comment by davideluque** [comment]
I ran into the problem that Capistrano Puma basic tasks were not showing up (restart, stop, start). This happens because, in Capistrano Puma 5.0, the tasks were moved to the service manager modules,

After

    require "capistrano/puma"
    install_plugin Capistrano::Puma

be sure to add:

    install_plugin Capistrano::Puma::Daemon

or if you use Systemd

    install_plugin Capistrano::Puma::Systemd

then all tasks should show up now and Puma should restart after deployment.

Note that this is incompatible with Puma 5+ as daemonization support was removed.

Source: https://github.com/seuros/capistrano-puma/issues/310

**Comment by mormorbump** [comment]
Since upgrading to Rails 6 I seem to have this problem too.
puma: Version 4.3.7 
ruby 2.7.1-p83
rails 6
capistrano3-puma: 5

**Comment by mormorbump** [comment]
It didn't work with'pumactl' in my environment, so I rewrote it to the puma command.

```
namespace :puma do
	Rake::Task[:restart].clear_actions

	desc "Overwritten puma:restart task"
	task :restart do
		on roles(:app) do |host|
			within current_path do
				# MEMO: pumctl is don`t work
				execute :puma, "-S #{fetch(:puma_state)} -C #{fetch(:puma_conf)} phased-restart"
			end
		end
	end

```

**Comment by mormorbump** [comment]
sorry, this code is not available.
https://github.com/seuros/capistrano-puma/issues/237#issuecomment-774466026


When "pumactl restart" failed, I noticed that the following log was output.

log/puma.error.log

```
/home/web_site/.rbenv/versions/2.7.1/bin/bundle:23:in `load': cannot load such file -- /home/web_site/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle (LoadError)
```

As you can see in this article, it seems to happen when you "puma restart" with "ruby2.7".

http://blog.cloud-mes.com/2020/04/06/fix-puma-failed-to-restart-in-ruby-2-dot-7-1/



As shown in this article, I solved it by typing the following command.
```
gem install bundler --default -v "1.17.3"
gem install bundler
```
