### ISSUE TITLE
`puma` no such file or directory

### ISSUE THREAD

**Issue by rejacobson** [seuros/capistrano-puma#250]
I have a rails 5 project with puma 3.9.1 listed in my Gemfile.

I'm trying to deploy the project to a server but when it tries to start puma it fails with this error:

```
$ cap production puma:start --trace
00:00 puma:start
  using conf file /var/www/app/shared/puma.rb
  01 puma -C /var/www/app/shared/puma.rb --daemon
  01 /usr/bin/env: ‘puma’
  01 : No such file or directory
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as apps@66.175.220.130: puma exit status: 127
puma stdout: Nothing written
puma stderr: /usr/bin/env: ‘puma’: No such file or directory
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/sshkit-1.14.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/sshkit-1.14.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
SSHKit::Command::Failed: puma exit status: 127
puma stdout: Nothing written
puma stderr: /usr/bin/env: ‘puma’: No such file or directory
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/sshkit-1.14.0/lib/sshkit/command.rb:99:in `exit_status='
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/sshkit-1.14.0/lib/sshkit/backends/netssh.rb:167:in `execute_command'
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/sshkit-1.14.0/lib/sshkit/backends/abstract.rb:141:in `block in create_command_and_execute'
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/sshkit-1.14.0/lib/sshkit/backends/abstract.rb:141:in `tap'
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/sshkit-1.14.0/lib/sshkit/backends/abstract.rb:141:in `create_command_and_execute'
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/sshkit-1.14.0/lib/sshkit/backends/abstract.rb:74:in `execute'
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/capistrano3-puma-3.1.1/lib/capistrano/tasks/puma.rake:26:in `block (6 levels) in eval_rakefile'
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/sshkit-1.14.0/lib/sshkit/backends/abstract.rb:93:in `with'
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/capistrano3-puma-3.1.1/lib/capistrano/tasks/puma.rake:25:in `block (5 levels) in eval_rakefile'
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/sshkit-1.14.0/lib/sshkit/backends/abstract.rb:85:in `within'
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/capistrano3-puma-3.1.1/lib/capistrano/tasks/puma.rake:24:in `block (4 levels) in eval_rakefile'
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/capistrano3-puma-3.1.1/lib/capistrano/puma.rb:9:in `puma_switch_user'
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/capistrano3-puma-3.1.1/lib/capistrano/tasks/puma.rake:14:in `block (3 levels) in eval_rakefile'
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/sshkit-1.14.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/sshkit-1.14.0/lib/sshkit/backends/abstract.rb:29:in `run'
/home/ryan/.rvm/gems/ruby-2.3.3@app/gems/sshkit-1.14.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => puma:start
```

I noticed that it's trying to run this:

`puma -C /var/www/app/shared/puma.rb --daemon`

I have puma installed as a gem in the project, and not a system gem, so just a plain call to `puma` won't work.

It should be:

`bundle exec puma  -C /var/www/app/shared/puma.rb --daemon`

In `lib/capistrano/tasks/puma.rake` there is a :start task that uses this to start puma:

`execute :puma, "-C #{fetch(:puma_conf)} --daemon"`

If I change that to:

`execute :bundle, :exec, :puma, "-C #{fetch(:puma_conf)} --daemon"`

Then everything works as expected and there are no issues.

Is there a reason that the rake task isn't using bundle exec in the first place?

I have to wonder if I'm missing something because I don't think I should have to install puma as a system gem or monkey patch code to get this working.

**Comment by rejacobson** [comment]
I managed to solve this issue by including these lines in my config/deploy.rb file:

```
SSHKit.config.command_map.prefix[:puma].push("bundle exec")
SSHKit.config.command_map.prefix[:pumactl].push("bundle exec")
```

This prefixes any calls to `puma` or `pumactl` with `bundle exec`

I discovered this feature of SSHKit from [this stackoverflow answer](https://stackoverflow.com/a/20933596)

I also had to downgrade the version of puma from `3.9.1` to `3.8.2` because of this issue:

[Restarting via SIGUSR2 broken in 3.9.0 works in 3.8.2](https://github.com/puma/puma/issues/1308)

Hopefully this info is useful for anyone else who runs into the same thing I did.
