### ISSUE TITLE
Puma is using wrong Ruby version

### ISSUE THREAD

**Issue by swigrid** [seuros/capistrano-puma#256]
When I deploy Puma is not restarted. Command which is used to restart is missing prefix `/usr/local/rvm/bin/rvm ruby-2.3.1@mff_v2 do `. 

It is just executed like this:
`bundle exec puma -C /var/www/mff_v2/shared/config/puma.rb --daemon`

If I compare other command executed by Capistrano, they all are prefixed with rvm and Ruby version
for example:
`/usr/local/rvm/bin/rvm ruby-2.3.1@mff_v2 do bundle exec rake 'assets:clean[2]'`

So my deployment ending with this error log:

```
00:50 puma:start
      using conf file /var/www/mff_v2/shared/config/puma.rb
      01 bundle exec puma -C /var/www/mff_v2/shared/config/puma.rb --daemon
      01 bundler: failed to load command: puma (/var/www/mff_v2/shared/bundle/ruby/2.3.0/bin/puma)
      01 LoadError: incompatible library version - /var/www/mff_v2/shared/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/puma_http11.so
      01   /var/www/mff_v2/shared/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/server.rb:15:in `require'
      01   /var/www/mff_v2/shared/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/server.rb:15:in `<top (required)>'
      01   /var/www/mff_v2/shared/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/runner.rb:1:in `require'
      01   /var/www/mff_v2/shared/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/runner.rb:1:in `<top (required)>'
      01   /var/www/mff_v2/shared/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/cluster.rb:1:in `require'
      01   /var/www/mff_v2/shared/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/cluster.rb:1:in `<top (required)>'
      01   /var/www/mff_v2/shared/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/launcher.rb:4:in `require'
      01   /var/www/mff_v2/shared/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/launcher.rb:4:in `<top (required)>'
      01   /var/www/mff_v2/shared/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/cli.rb:5:in `require'
      01   /var/www/mff_v2/shared/bundle/ruby/2.3.0/gems/puma-3.10.0/lib/puma/cli.rb:5:in `<top (required)>'
      01   /var/www/mff_v2/shared/bundle/ruby/2.3.0/gems/puma-3.10.0/bin/puma:6:in `require'
      01   /var/www/mff_v2/shared/bundle/ruby/2.3.0/gems/puma-3.10.0/bin/puma:6:in `<top (required)>'
      01   /var/www/mff_v2/shared/bundle/ruby/2.3.0/bin/puma:23:in `load'
      01   /var/www/mff_v2/shared/bundle/ruby/2.3.0/bin/puma:23:in `<top (required)>'
```

Is this an issue or configuration problem? I haven't found any option to specify rvm for Puma.
I'm using version `3.1.1`

**Comment by joshmn** [comment]
Also having this exact issue.

**Comment by seuros** [comment]
You are probably overwriting :rvm_map_bins

**Comment by piks3l** [comment]
Have you fixed this issue ? I happen to have same problem in a production env on Heroku

**Comment by swigrid** [comment]
no, this is my workaround

```
desc 'Puma reload'
task :puma_reload do
  on roles(:app) do
    execute "cd #{release_path} && kill -15 `lsof -i:9596 -t` && RAILS_ENV='#{fetch(:rails_env)}' /usr/local/rvm/bin/rvm ruby-2.3.1@mff_v2 do bundle exec puma -C /var/www/mff_v2/shared/config/puma.rb --daemon"
  end
end

after :deploy, :puma_reload
```

**Comment by zeeshangulzar** [comment]
Any update on this issue? I am facing the same issue? @swigrid give a solution but it is totally hard- coded

**Comment by nicozhang** [comment]
I also meet this problem.
just add 
```
append :rvm_map_bins, 'puma', 'pumactl'
```
in you  deploy.rb
