### ISSUE TITLE
i get this error:cannot load such file -- capistrano/puma

### ISSUE THREAD

**Issue by 85636682** [seuros/capistrano-puma#27]
gemfile

```
group :development, :test do
  gem 'capistrano', '~> 3.1.0'
  gem 'capistrano-rails',   '~> 1.1', require: false
  gem 'capistrano-bundler', '~> 1.1', require: false
  gem 'capistrano-rbenv', '~> 2.0', require: false
  gem 'capistrano3-puma', github: "seuros/capistrano-puma"
end
```

capfile

```
# Load DSL and Setup Up Stages
require 'capistrano/setup'

# Includes default deployment tasks
require 'capistrano/deploy'
# Includes tasks from other gems included in your Gemfile
#
# For documentation on these, see for example:
#
#   https://github.com/capistrano/rvm
#   https://github.com/capistrano/rbenv
#   https://github.com/capistrano/chruby
#   https://github.com/capistrano/bundler
#   https://github.com/capistrano/rails
#
# require 'capistrano/rvm'
require 'capistrano/rbenv'
require 'capistrano/puma'
# require 'capistrano/chruby'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'

# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob('lib/capistrano/tasks/*.cap').each { |r| import r }
```

when i run `cap production deploy`
i get this error

```
@reim ➜  mywy rbenv:(2.1.0-rc1) git:(master) ✗ cap production deploy --trace
cap aborted!
cannot load such file -- capistrano/puma
/Users/stephen/.rbenv/versions/2.1.0-rc1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/stephen/.rbenv/versions/2.1.0-rc1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/stephen/mywy/Capfile:18:in `<top (required)>'
/Users/stephen/.rbenv/versions/2.1.0-rc1/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_module.rb:25:in `load'
/Users/stephen/.rbenv/versions/2.1.0-rc1/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_module.rb:25:in `load_rakefile'
/Users/stephen/.rbenv/versions/2.1.0-rc1/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:637:in `raw_load_rakefile'
/Users/stephen/.rbenv/versions/2.1.0-rc1/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:94:in `block in load_rakefile'
/Users/stephen/.rbenv/versions/2.1.0-rc1/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/stephen/.rbenv/versions/2.1.0-rc1/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:93:in `load_rakefile'
/Users/stephen/.rbenv/versions/2.1.0-rc1/lib/ruby/gems/2.1.0/gems/capistrano-3.1.0/lib/capistrano/application.rb:24:in `load_rakefile'
/Users/stephen/.rbenv/versions/2.1.0-rc1/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:77:in `block in run'
/Users/stephen/.rbenv/versions/2.1.0-rc1/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/stephen/.rbenv/versions/2.1.0-rc1/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/Users/stephen/.rbenv/versions/2.1.0-rc1/lib/ruby/gems/2.1.0/gems/capistrano-3.1.0/lib/capistrano/application.rb:15:in `run'
/Users/stephen/.rbenv/versions/2.1.0-rc1/lib/ruby/gems/2.1.0/gems/capistrano-3.1.0/bin/cap:3:in `<top (required)>'
/Users/stephen/.rbenv/versions/2.1.0-rc1/bin/cap:23:in `load'
/Users/stephen/.rbenv/versions/2.1.0-rc1/bin/cap:23:in `<main>'
```

**Comment by kourindouhime** [comment]
and how did you solve it?

**Comment by alagu** [comment]
Removing ` , github: "seuros/capistrano-puma" ` worked for me.

**Comment by yuriytickets** [comment]
In my case that error was solved by choosing right rvm ruby version
`rvm use #{your-ruby-v} did the trick)`

**Comment by abhianair** [comment]
I got the same error.... how to solve??

**Comment by benwalks** [comment]
For future Googlers, I had a typo in my Capfile which was causing this issue. I had `require "capistrano/puma-nginx"` instead of `require "capistrano/puma/nginx"`.

Fixing the typo fixed the issue!
