### ISSUE TITLE
puma:restart fails with fstat error. puma:start works fine

### ISSUE THREAD

**Issue by kiddrew** [seuros/capistrano-puma#286]
When I run puma:restart, it kills the process but fails to restart it. Throws the following error:

```
/var/www/app/shared/bundle/ruby/2.5.0/gems/puma-4.0.0/lib/puma/binder.rb:299:in `for_fd': Bad file descriptor - fstat(2) (Errno::EBADF)
	from /var/www/app/shared/bundle/ruby/2.5.0/gems/puma-4.0.0/lib/puma/binder.rb:299:in `inherit_tcp_listener'
	from /var/www/app/shared/bundle/ruby/2.5.0/gems/puma-4.0.0/lib/puma/binder.rb:101:in `block in parse'
	from /var/www/app/shared/bundle/ruby/2.5.0/gems/puma-4.0.0/lib/puma/binder.rb:96:in `each'
	from /var/www/app/shared/bundle/ruby/2.5.0/gems/puma-4.0.0/lib/puma/binder.rb:96:in `parse'
	from /var/www/app/shared/bundle/ruby/2.5.0/gems/puma-4.0.0/lib/puma/runner.rb:153:in `load_and_bind'
	from /var/www/app/shared/bundle/ruby/2.5.0/gems/puma-4.0.0/lib/puma/single.rb:98:in `run'
	from /var/www/app/shared/bundle/ruby/2.5.0/gems/puma-4.0.0/lib/puma/launcher.rb:186:in `run'
	from /var/www/app/shared/bundle/ruby/2.5.0/gems/puma-4.0.0/lib/puma/cli.rb:80:in `run'
	from /var/www/app/shared/bundle/ruby/2.5.0/gems/puma-4.0.0/bin/puma:10:in `<top (required)>'
	from /var/www/app/shared/bundle/ruby/2.5.0/bin/puma:23:in `load'
	from /var/www/app/shared/bundle/ruby/2.5.0/bin/puma:23:in `<main>'
	from /var/www/app/shared/bundle/ruby/2.5.0/bin/ruby_executable_hooks:24:in `eval'
	from /var/www/app/shared/bundle/ruby/2.5.0/bin/ruby_executable_hooks:24:in `<main>'
```

Running puma:start immediately after that works fine.

**Comment by vijayanandnandam** [comment]
same error face by me as well

**Comment by andrepcg** [comment]
Same problem here

**Comment by xifengzhu** [comment]
Same problem here

**Comment by micred** [comment]
As detailed here https://github.com/puma/puma/issues/1957#issuecomment-552540416 I solved adding to deploy.rb the following setting:
`set :puma_restart_command, 'bundle exec --keep-file-descriptors puma'

If you've already made your first deploy you should run `cap puma:config` to update puma.rb in the server.

**Comment by vast** [comment]
Hi guys,

In my case restart fails due to bundler error:
```ruby
==> log/puma_error.log <==
/home/deploy/.rbenv/versions/2.7.1/bin/bundle:23:in `load': cannot load such file -- /home/deploy/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle (LoadError)
	from /home/deploy/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
```

I tried reinstalling bundler. Still no luck.

Any ideas?

**Comment by kaspernj** [comment]
Same problem here. The `keep-file-descriptors` doesn't work for me.

**Comment by loma** [comment]
same problem here for rails 6.x with puma 3.x
but it's working fine with rails 5.x with puma 3.x
I tested with the same server, i guess it's the problem with rails 6

**Comment by loma** [comment]
a further test, after resetting the environment and init all deployment workspace. The issues resolved.
working fine with rails 6 with puma 3 and 4
simply just reset the workspace/deployment directory.
