### ISSUE TITLE
after gem updates deploy fails with can't find service

### ISSUE THREAD

**Issue by salex** [seuros/capistrano-puma#369]
A few weeks ago I added a rails 7.1 upgrade at a branch. This was about the time you released a version and capistrano also released a version.

I dug myself a hole that I could not get out of when I tried to deploy my current 7.0 version to a staging server.

I've had numerous error that I tried different things. Even corrupted my Gemfile.lock that I had to rebuild.

it comes down to the current deploy error:

```ruby
    01 /bin/systemctl --user restart ptgolf_puma_staging
      01 Failed to restart ptgolf_puma_staging.service: Unit ptgolf_puma_staging.service not found.
#<Thread:0x0000000153e02078 /Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sshkit-1.21.5/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
/Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sshkit-1.21.5/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as developer@staging.local: /bin/systemctl exit status: 5 (SSHKit::Runner::ExecuteError)
/bin/systemctl stdout: Failed to restart ptgolf_puma_staging.service: Unit ptgolf_puma_staging.service not found.
/bin/systemctl stderr: Nothing written
	from /Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sshkit-1.21.5/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sshkit-1.21.5/lib/sshkit/command.rb:97:in `exit_status=': /bin/systemctl exit status: 5 (SSHKit::Command::Failed)
/bin/systemctl stdout: Failed to restart ptgolf_puma_staging.service: Unit ptgolf_puma_staging.service not found.
/bin/systemctl stderr: Nothing written
	from /Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sshkit-1.21.5/lib/sshkit/backends/netssh.rb:170:in `execute_command'
	from /Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
	from <internal:kernel>:90:in `tap'
	from /Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
	from /Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:80:in `execute'
	from /Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/capistrano3-puma-6.0.0.beta.1/lib/capistrano/puma/systemd.rb:55:in `sudo_if_needed'
	from /Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/capistrano3-puma-6.0.0.beta.1/lib/capistrano/puma/systemd.rb:60:in `execute_systemd'
	from /Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/capistrano3-puma-6.0.0.beta.1/lib/capistrano/tasks/systemd.rake:101:in `block (3 levels) in eval_rakefile'
	from /Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	from /Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:31:in `run'
	from /Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sshkit-1.21.5/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as developer@staging.local: /bin/systemctl exit status: 5
/bin/systemctl stdout: Failed to restart ptgolf_puma_staging.service: Unit ptgolf_puma_staging.service not found.
/bin/systemctl stderr: Nothing written
```
It can't find the service file but I can login to the staging server and do::

```
sudo systemctl restart ptgolf_puma_staging.service
```
and it words fine.

I've been going in circles for the last week but I think it's yours.

**Comment by salex** [comment]
Guess I should read closed issues a little more closely. [issue](https://github.com/seuros/capistrano-puma/issues/352) had a last comment:

_For anyone else having this problem, it looks like :puma_systemctl_user has switched from defaulting to :system to :user. Adding set :puma_systemctl_user, :system to my deploy.rb file fixed it so it worked like the previous version._

 that solved my problem.

I was probably a release back that still worked. The updates broke what I had configured.
