### ISSUE TITLE
NoMethodError: undefined method `verbosity' for "/usr/bin/env puma:start\n":String

### ISSUE THREAD

**Issue by itsNikolay** [seuros/capistrano-puma#76]
```shell
** Invoke puma:smart_restart (first_time)
** Execute puma:smart_restart
** Invoke puma:restart (first_time)
** Execute puma:restart
DEBUG [0f230bae] Running /usr/bin/env if test ! -d /home/deploy/apps/aakr_staging_ru/current; then echo "Directory does not exist '/home/deploy/apps/aakr_staging_ru/current'" 1>&2; false; fi on 104.131.0.0
DEBUG [0f230bae] Command: if test ! -d /home/deploy/apps/aakr_staging_ru/current; then echo "Directory does not exist '/home/deploy/apps/aakr_staging_ru/current'" 1>&2; false; fi
DEBUG [0f230bae] Finished in 3.251 seconds with exit status 0 (successful).
DEBUG [41e5db22] Running /usr/bin/env [ -f /home/deploy/apps/aakr_staging_ru/shared/tmp/pids/puma.pid ] on 104.131.0.0
DEBUG [41e5db22] Command: [ -f /home/deploy/apps/aakr_staging_ru/shared/tmp/pids/puma.pid ]
DEBUG [41e5db22] Finished in 0.500 seconds with exit status 1 (failed).
cap aborted!
NoMethodError: undefined method `verbosity' for "/usr/bin/env puma:start\n":String
/home/itsnikolay/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.2.0/lib/sshkit/formatters/pretty.rb:10:in `write'
/home/itsnikolay/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.2.0/lib/sshkit/backends/printer.rb:14:in `block in execute'
/home/itsnikolay/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.2.0/lib/sshkit/backends/printer.rb:13:in `tap'
/home/itsnikolay/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.2.0/lib/sshkit/backends/printer.rb:13:in `execute'
/home/itsnikolay/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/capistrano3-puma-0.8.2/lib/capistrano/tasks/puma.cap:103:in `block (6 levels) in <top (required)>'
/home/itsnikolay/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.2.0/lib/sshkit/backends/abstract.rb:89:in `with'
/home/itsnikolay/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/capistrano3-puma-0.8.2/lib/capistrano/tasks/puma.cap:97:in `block (5 levels) in <top (required)>'
/home/itsnikolay/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.2.0/lib/sshkit/backends/abstract.rb:81:in `within'
/home/itsnikolay/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/capistrano3-puma-0.8.2/lib/capistrano/tasks/puma.cap:96:in `block (4 levels) in <top (required)>'
/home/itsnikolay/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.2.0/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/home/itsnikolay/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.2.0/lib/sshkit/backends/netssh.rb:54:in `run'
/home/itsnikolay/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.2.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => puma:restart
```
I try to use `jungle` to start pamas

My deploy/config.rb file

```ruby
set :puma_init_active_record, true

set :rbenv_type, :system
set :rbenv_ruby, '2.1.3'
set :rbenv_prefix, "RBENV_ROOT=#{fetch(:rbenv_path)} RBENV_VERSION=#{fetch(:rbenv_ruby)} #{fetch(:rbenv_path)}/bin/rbenv exec"
set :rbenv_map_bins, %w{rake gem bundle ruby rails}
set :linked_files, %w{config/database.yml}
set :linked_dirs, %w{bin log tmp/pids tmp/cache tmp/sockets vendor/bundle public/system public/uploads}

namespace :deploy do
  task :restart do
    invoke 'puma:jungle:restart'
  end
end
```

My Capfile
```ruby
require 'capistrano/setup'
require 'capistrano/deploy'

require 'capistrano/rbenv'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
require 'capistrano/puma'
require 'capistrano/puma/jungle'
require 'capistrano/puma/monit'
require 'capistrano/puma/nginx'
```

And one more question, how to set deploy task to run jungle ?
In readme there's nothing about it. =(

**Comment by yugonhiphop** [comment]
I am also getting the same issue. but I am not using jungle. only capistrano capistrano-puma and puma and nginx reverse proxy on AWS server.

**Comment by rcrogers** [comment]
Also getting this, not using jungle.

**Comment by pelcasandra** [comment]
Being a couple hours around this too, finally solved with [this](http://portalshit.net/2014/01/26/using-capistrano3).

```
gem 'sshkit', github: 'capistrano/sshkit'
```
